boostcampwm-2022/web17-waglewagle

rest/src/main/java/com/waglewagle/rest/user/OauthMethod.java, rest/src/main/java/com/waglewagle/rest/user/User.java, rest/src/main/java/com/waglewagle/rest/user/UserController.java, rest/src/main/java/com/waglewagle/rest/user/UserRepository.java, rest/src/main/java/com/waglewagle/rest/user/UserService.java, rest/src/main/java/com/waglewagle/rest/user/dto/LoginResponseDTO.java, rest/src/main/java/com/waglewagle/rest/user/dto/UsernameLoginDTO.java, rest/src/main/resources/general.yml, rest/src/test/java/com/waglewagle/rest/user/UserControllerTest.java, rest/src/test/java/com/waglewagle/rest/user/UserRepositoryTest.java
- userRepository, userService, userController, DTOs 구현
- username을 활용한 로그인 구현
- userController와 userRespository를 위한 test 코드 구현
- username을 활용한 로그인 테스트 코드 작성
```
POST /api/v1/user/login
Request Body
{ username: string }
Response Body
{ userId: Long }
```
=> [feat] username을 활용한 login 구현

frontend/pages/community/[id].tsx, frontend/util/TrieSearchEngine.ts, frontend/utils/SearchEngine.ts, frontend/utils/TrieSearchEngine.ts
- Trie를 기반으로 검색 자동완성을 구현하기로 함.
- 다른 전략은 Test와 Refactor를 진행하면서 시간이 있다면 하기로 함.
- TrieSearchEngine는 TrieNode로 이루어진 Trie 자료구조를 기반으로 만들어진 자동완성을 위한 단어 검색 엔진이다.
- TrieNode는 isCompleteWord와 children으로 구성되어 있다.
> isCompleteWord : 현재 단어가 완결된 단어로써 커뮤니티 단어 데이터에 있는지 확인한다. 즉, 현재 노드가 커뮤니티에 포함된 단어의 마지막 **‘문자’** 노드인지 확인해주는 flag이다.
children : 현재 단어에 이어지는 문자들을 TrieNode인 자식으로 갖는다.
> 
1) 단어를 반복문 돌면서 각 글자를 Trie 자료구조로 만든다.
2) 현재 글자가 자식 노드에 있다면, 자식 노드로 현재 노드를 이동시킨다.
3) 현재 글자가 자식 노드에 없다면, 현재 글자를 자식 노드에 추가한다.
1) getSearchKeywordNode를 통해서, 어느 노드부터 dfs로 탐색을 시작할지 결정한다.
2) dfs를 시작하는 노드부터, dfsNodeSearch로 isCompleteWord가 있는 노드를 찾아서 해당 노드까지의 경로(검색 단어에 추가될 단어)를 결과 배열에 추가한다.
3) 검색 단어에 추가될 단어를 붙여서 최종 검색 결과로 반환한다.
1) 검색 단어의 문자들을 순회한다.
1. 만약 현재 노드의 자식에 순회중인 문자가 없다면, 검색 단어가 서치엔진 Trie 데이터에 없다는 의미이므로 검색 단어가 커뮤니티에 없다고 판단하여, …
=> [Feat] Day02. 검색 자동완성 구현

frontend/components/common/LoginModalContent.tsx, frontend/components/community/KeywordBubble.tsx, frontend/sass/components/common/Modal.module.scss
- 성현님이 작업해놓으신 키워드 그룹을 모달로 띄울 수 있어야했음.
- 로그인시, 로그인 처리가 되지 않는 에러가 있었음.
https://user-images.githubusercontent.com/69471032/205120446-8708266e-8594-490f-a7d1-8859a6a1216d.mp4
- 키워드 버블 클릭시, 키워드 그룹 입장 구현 (아직 키워드 그룹 모달창은 없음)
- 로그인 API를 동기처리하지 않아서 발생하던 에러였음.
=> [Feat] 키워드 그룹 모달 병합

rest/src/main/java/com/waglewagle/rest/community/CommunityController.java, rest/src/main/java/com/waglewagle/rest/community/CommunityDTO.java, rest/src/main/java/com/waglewagle/rest/community/CommunityRepository.java, rest/src/main/java/com/waglewagle/rest/community/CommunityService.java, rest/src/main/java/com/waglewagle/rest/communityUser/CommunityUser.java, rest/src/main/java/com/waglewagle/rest/communityUser/CommunityUserController.java, rest/src/main/java/com/waglewagle/rest/communityUser/CommunityUserDTO.java, rest/src/main/java/com/waglewagle/rest/communityUser/CommunityUserRepository.java, rest/src/main/java/com/waglewagle/rest/communityUser/CommunityUserService.java
- 내가 가입한 커뮤니티에 대한 정보를 얻을 수 있어야 함.
- 커뮤니티에 가입할 수 있어야 함.
- 가입된 커뮤니티 정보 API구현
- 커뮤니티 가입 API 구현
=> [feat] 커뮤니티 가입 및 가입 커뮤니티 조회 기능

oauth/.gitignore, oauth/package-lock.json, oauth/package.json, oauth/src/app.ts, oauth/src/conf/env.ts, oauth/src/conf/orm.config.ts, oauth/src/database/data-source.ts, oauth/src/domain/error/not-found.ts, oauth/src/domain/index.ts, oauth/src/domain/oauth/oauth.controller.ts, oauth/src/domain/oauth/oauth.service.ts, oauth/src/domain/oauth/user.entity.ts, oauth/src/domain/oauth/user.repository.ts, oauth/src/main.ts, oauth/src/types/request-handler.type.ts, oauth/src/types/request-method.type.ts, oauth/src/util/utils.ts, oauth/tsconfig.json, rest/src/main/java/com/waglewagle/rest/communityUser/CommunityUser.java, rest/src/main/java/com/waglewagle/rest/communityUser/CommunityUserController.java, rest/src/main/java/com/waglewagle/rest/communityUser/CommunityUserDTO.java, rest/src/main/java/com/waglewagle/rest/communityUser/CommunityUserService.java, rest/src/main/java/com/waglewagle/rest/keyword/KeywordController.java, rest/src/main/java/com/waglewagle/rest/keyword/KeywordDTO.java, rest/src/main/java/com/waglewagle/rest/keyword/KeywordRepository.java, rest/src/main/java/com/waglewagle/rest/keyword/KeywordService.java, rest/src/main/java/com/waglewagle/rest/keyword/association/DumbAssociateCalculator.java
Node.JS를 활용한 Github Oauth 서버 구현
`GET` www.waglewagle.link/oauth2/login/github
=> [feat] Github Oauth 서버 구현

frontend/components/common/StartButton.tsx, frontend/config.ts
- 배포 이후 데모 발표 때 확인해보니 시작하기 버튼 클릭 시 localhost로 연결되고 있었음
- .env에 host를 추가하고 config에 HOST를 추가하여 개발과 배포환경의 host를 신경쓰지 않아도 되도록 변경함
=> [Fix] Week04 release Hotfix

frontend/components/common/StartButton.tsx, frontend/components/community/KeywordAddModal.tsx, frontend/components/community/KeywordAdder.tsx, frontend/components/community/KeywordAssociated.tsx, frontend/config.ts, frontend/constants/constants.ts, frontend/pages/_document.tsx, frontend/pages/community/[id].tsx, frontend/sass/components/common/LoginModalContent.module.scss, frontend/sass/components/community/AutoCompleteFormLayout.module.scss, frontend/sass/components/community/KeywordAddModal.module.scss, frontend/sass/components/community/KeywordAssociated.module.scss, frontend/sass/components/community/KeywordBubble.module.scss, frontend/sass/components/community/MyKeyword.module.scss, frontend/sass/components/community/SearchResultListLayout.module.scss, frontend/sass/components/community/keyword/KeywordMain.module.scss, frontend/sass/components/community/keyword/KeywordUserList.module.scss, frontend/sass/components/community/keyword/Sidebar.module.scss, frontend/sass/components/home/HomeDescription.module.scss, frontend/sass/components/home/HomeTitle.module.scss, frontend/sass/globals.scss, frontend/sass/variables.scss
- 
- 추천 키워드 UI 연결
- 나눔 북극성 웹폰트로 변경
- Noto Sans 폰트 추가 및 적용
- 추천 말풍선 UI 구현 및 API 연결
- 추천 말풍선 스타일링
=> [Feat] 키워드 추천 API 클라이언트 연결하기

frontend/circlepacker/Circle.ts, frontend/circlepacker/CircleContainer.ts, frontend/components/community/KeywordBubble.tsx, frontend/components/community/KeywordBubbleChart.tsx, frontend/sass/components/community/KeywordBubble.module.scss
- 불필요한 event listener가 쌓이고, JS Heap 메모리 사용량이 많았음.
- 크롬 개발자 도구를 통해 불필요한 상태를 제거하여 Eventlistener와 Heap 메모리 제거
- 불필요한 circle 계산 작업 제거
=> [Fix] circlepacker 성능 향상

rest/src/main/java/com/waglewagle/rest/keyword/repository/KeywordRepository.java, rest/src/main/java/com/waglewagle/rest/keyword/repository/KeywordUserRepository.java, rest/src/main/java/com/waglewagle/rest/keyword/service/KeywordService.java
해당 유저가 이미 가입한 키워드라면, http staus 404, errorMessage "이미 가입된 키워드입니다." 반환
=> [Fix] 키워드 가입 API, POST keyword/join, 중복가입 해결

frontend/apis/apis.ts, frontend/components/common/MouseModal.tsx, frontend/components/community/KeywordBubble.tsx, frontend/components/community/KeywordBubbleChart.tsx, frontend/components/community/KeywordGroupEnterModalContent.tsx, frontend/components/community/KeywordGroupInfoModalContent.tsx, frontend/components/community/MainKeywordHandlerLayout.tsx, frontend/components/community/MyKeywordHighlight.tsx, frontend/components/main/CommunityList.tsx, frontend/constants/constants.ts, frontend/hooks/useJoinKeywordMutation.tsx, frontend/pages/community/[id].tsx, frontend/sass/components/common/MouseModal.module.scss, frontend/sass/components/community/KeywordAdderLayout.module.scss, frontend/sass/components/community/KeywordBubble.module.scss, frontend/sass/components/community/KeywordGroupEnterModalContent.module.scss, frontend/sass/components/community/KeywordGroupInfoModalContent.module.scss, frontend/sass/components/community/MainKeywordHandlerLayout.module.scss, frontend/sass/components/community/MyKeywordHighlight.module.scss, frontend/types/types.ts
- 키워드 버블의 키워드가 내 키워드인지 확인하는 함수 구현
- isHighlight 토글 구현
- 내 키워드 강조 구현
- 성능적으로 문제가 생길 부분이 없을까?
=> [Feat] 내 키워드 강조 구현

rest/.gitignore, rest/build.gradle, rest/src/main/resources/logback-spring.xml
=> [feat] 로링 프레임워크, Logback 설정

frontend/apis/apis.ts, frontend/components/community/KeywordBubble.tsx, frontend/components/community/KeywordGroupInfoModalContent.tsx, frontend/components/community/keyword-group/KeywordGroupModalContent.tsx, frontend/components/community/keyword-group/KeywordGroupUserList.tsx, frontend/pages/community/[id].tsx, frontend/pages/main.tsx
- 유저 피드백에서 나온 버그 반영하여 버그 수정
- 스레드 유저 목록 제목 바뀌지 않는 현상 해결
- 커뮤니티 페이지 접속시 최근 접속 기록 갱신되지 않는 현상 해결
- 유저목록 접속 중 유저 먼저 보이지 않는 형상 해결
- 키워드 입장하기 후에 모달이 닫히지 않는 현상 해결
- 로그인 아닌 상태에서 메인 페이지 이동 시 무한 로딩 현상 해결
- 모달 클릭 시 모달이 이동하는 현상 해결
=> [Fix] 유저 피드백을 통한 버그 수정

rest/src/main/java/com/waglewagle/rest/thread/service/ThreadService.java
Thread의 parent Thread를 검증하는 과정에 있던 논리적 오류 수정
Thread의 parent Thread를 검증하는 과정에 논리적 오류가 있어 유효한 경우에 exception이 발생하는 문제가 있었음.
변수 명을 수정하였으며, validation 로직을 변경함
=> [fix] 쓰레드 생성 API 버그 수정

rest/src/main/java/com/waglewagle/rest/keyword/service/KeywordService.java
=> [fix] 키워드 머지 관련 권한 검증 로직 수정

frontend/sass/animations.scss, frontend/sass/components/admin/UserControl.module.scss, frontend/sass/components/common/LoginModalContent.module.scss, frontend/sass/components/common/Modal.module.scss, frontend/sass/components/common/MouseModal.module.scss, frontend/sass/components/community/CommunityHeader.module.scss, frontend/sass/components/community/keyword-add-modal/EnterButton.module.scss, frontend/sass/components/community/keyword-add-modal/KeywordAddModalContent.module.scss, frontend/sass/components/community/keyword-add-modal/MyKeyword.module.scss, frontend/sass/components/community/keyword-add-modal/MyKeywordList.module.scss, frontend/sass/components/community/keyword-adder/AutoCompleteFormLayout.module.scss, frontend/sass/components/community/keyword-adder/KeywordAdderLayout.module.scss, frontend/sass/components/home/HomeDescription.module.scss, frontend/sass/components/home/HomeHero.module.scss, frontend/sass/components/main/CommunityItem.module.scss, frontend/sass/components/main/DefaultProfile.module.scss, frontend/sass/components/main/MainHeader.module.scss, frontend/sass/mixins.scss
=> [Refactor] 공통 스타일 분리

rest/src/main/java/com/waglewagle/rest/keyword/service/KeywordService.java, rest/src/test/java/com/waglewagle/rest/keyword/service/KeywordServiceTest.java
- Keyword Service 테스트 코드
- createKeyword
- joinKeyword 
- 안정성을 위한 테스트 코드 추가
- createKeyword 성공 케이스 및 실패 케이스 테스트 코드
- joinKeyword 성공 케이스 및 실패 케이스 테스트 코드
=> [feat] keywordService 테스트 코드 추가

frontend/.eslintrc.json, frontend/hooks/useJoinBoostcampCommunity.tsx, frontend/package-lock.json, frontend/pages/community/[id].tsx, frontend/pages/index.tsx, frontend/pages/main.tsx
- 수월한 데모를 위해 첫 로그인 시, 부캠 커뮤니티에 자동으로 가입하도록 함.
- 이전에 에러가 나던 코드를 커스텀 훅으로 분리하고, 에러를 수정함.
=> [Fix] 첫 로그인 시, 부캠 커뮤니티 가입

frontend/.eslintrc.json, frontend/components/community/keyword-bubble-chart/KeywordBubbleChart.tsx, frontend/hooks/useJoinBoostcampCommunity.tsx, frontend/package-lock.json, frontend/pages/community/[id].tsx, frontend/pages/index.tsx, frontend/pages/main.tsx, frontend/utils/circlepacker/CircleContainer.test.ts, frontend/utils/circlepacker/CircleContainer.ts
- 현재의 테스트 내용이 물리엔진을 확인하기 부족한 것 같아서 수정을 진행함
- 테스트 내용 보완
- 물리엔진 리팩토링을 시도했지만, 알 수 없는 버그로 인해 내일 발표 준비를 위해서 포기함
- 이슈에 발행해두고 추후 수정 예정
```ts
it('CircleContainer 초기화 테스트', () => {
expect(circleContainer.circles).toEqual({});
expect(circleContainer['width']).toEqual(CONTAINER_MOCK_WIDTH);
expect(circleContainer['height']).toEqual(CONTAINER_MOCK_HEIGHT);
});
it('하나의 원을 생성한다.', () => {
circleContainer.addCircle('1', 1);
expect(Object.keys(circleContainer.circles)).toHaveLength(1);
expect(circleContainer.circles['1']).toMatchObject({ id: '1' });
});
it('이미 있는 원 일 경우, 추가가 아닌 갱신', () => {
circleContainer.addCircle('1', 1);
const initialCircle = { ...circleContainer.circles['1'] };
circleContainer.addCircle('1', 2);
const updatedCircle = { ...circleContainer.circles['1'] }; …
```
=> [Test] 물리엔진 테스트코드 수정

frontend/components/main/CommunityItem.tsx, frontend/components/main/CommunityList.tsx, frontend/types/types.ts
=> [Feat] 메인 페이지 커뮤니티 유저 수 표시

.github/workflows/frontend-main-cd.yml, .github/workflows/frontend-release-cd.yml
=> [Env] fe/main 브랜치 cd 스크립트
