boostcampwm-2022/web17-waglewagle

frontend/components/community/AutoComplete.tsx
frontend/components/community/KeywordAddModal.tsx
frontend/components/community/KeywordBubble.tsx
frontend/components/community/KeywordBubbleChart.tsx
frontend/components/community/index.ts
frontend/pages/community/[id].tsx
frontend/sass/components/community/KeywordBubble.module.scss
frontend/sass/components/community/KeywordBubbleChart.module.scss
frontend/types/types.ts

- 배치 알고리즘을 구현하기 전에 버블 차트 스타일 작업을 먼저 진행하기로 함.
- 일단 눈에 보이는 것이 먼저 나와야 작업이 진행되는 이유가 하나였고
- 미리 구현해두면 배치 알고리즘 작업을 진행하며 변경 사항을 눈으로 볼 수 있기 때문 (테스트 코드처럼)
- 또한 하나를 미리 끝내두고 가야 디버깅을 할 때 문제 인식이 더 정확하게 될 수 있다고 판단하기도 하였음.
- 키워드 목록 Mocking
- 키워드 컨테이너 레이아웃 생성
- 키워드 버블 컴포넌트 생성 (지정 width 넘어가면 ... 이 되도록 설정)
- 키워드 버블 호버 시 인터랙션 구현
- 배치를 위한 방법들에 대해 더 찾아보고, 논의하기로 함.
- 논의 이후 구현은 다음 날로 이동 (2022.11.24.)
- 객체지향을 통해 물리엔진을 구현, 이 물리엔진을 통해서 충돌과 중력을 통해 자연스러운 circle packing을 통해서 버블차트를 구현하기로함.

[Feat] 버블 차트 레이아웃 구현

---

frontend/components/common/LoginModalContent.tsx
frontend/components/common/StartButton.tsx
frontend/components/community/CommunityLayout.tsx
frontend/components/home/HomeHero.tsx
frontend/pages/community/[id].tsx
frontend/sass/components/common/LoginModalContent.module.scss
frontend/sass/components/community/CommunityHeader.module.scss
frontend/sass/components/community/CommunityLayout.module.scss
frontend/sass/components/community/KeywordBubbleChart.module.scss
frontend/sass/globals.scss

- username 로그인을 삭제하고, oauth 로그인만 남겨둠.
- spring security의 기능으로 인해서 github authorization으로 연결하지 않고, api만 요청함. 이를 통해서 client_id가 노출되지 않는 보안적인 장점이 있음.
- UI 수정작업
- API를 연결함. API 에러로 현재는 동작하지 않음.
- z-index와 width, height, position 미적용으로 데이터 시각화 부분에 덮여서 헤더가 클릭되지 않던 에러를 해결함. 해당 트러블 슈팅 정리해두었음. [보러가기](https://enormous-iguanadon-33a.notion.site/z-index-position-e73e996420634ee2b80f8b5b1816e09c)
- spring security를 빼고 nextjs의 rewrite를 사용해서 client_id를 숨길 수 있음.

[Feat] 로그인 모달창 api 연결 및 모달창 UI 수정

---

.github/workflows/rest-cicd.yml

- appleboy/ssh action에서 nohup ... & 명령어로 어플리케이션을 background에서 실행하였지만, 러너의 foreground에서 실행되던 버그가 발생
- CI/CD 과정에서 빌드 실패 오류 발생
- Github Oauth2 인증 및 인가에 필요한 환경 변수가 설정된 파일 추가.

[fix] Github Oauth2 관련 환경 변수 반영 && 어플리케이션 백그라운드 실행 버그 수정

---

rest/src/main/java/com/waglewagle/rest/communityUser/CommunityUser.java
rest/src/main/java/com/waglewagle/rest/communityUser/CommunityUserRepository.java
rest/src/main/java/com/waglewagle/rest/communityUser/CommunityUserService.java
rest/src/main/java/com/waglewagle/rest/keyword/KeywordController.java
rest/src/main/java/com/waglewagle/rest/user/UserController.java
rest/src/main/java/com/waglewagle/rest/user/UserService.java
rest/src/main/java/com/waglewagle/rest/user/dto/UserInfoDTO.java

```
GET '/api/v1/user/me'
Query Params
community-id : string(?community-id=1 과 같이 보내주셔야 합니다. ?community-id="1" 안되요.)
Response Body
{
userId: string,
username: string,
profileImageUrl: string,
role: string,
isFirstInCommunity: boolean
}
```
- 2022.12.02
초기 로그인인지 확인할 수 없어서, 키워드 입력 모달을 띄울 수 없습니다.
user/me response body에 초기 로그인인지 확인할 수 있는 정보가 필요합니다.
- 2022.12.02
관리자 페이지 접근 권한을 막기 위해 /user/me에 role도 같이 와야합니다.
1. `CommunityUser` Table에 `isFirstVisit` boolean 컬럼을 추가하였음.
2. `userId` 와 `communityId` 를 통해 조회
3. `CommunityUser` Table : `userId` 컬럼과 `communityId` 컬럼의 조합을 유니크 키로 등록하였음.
- 이후 쿼리 실행계획에서 인덱스가 잘 작동하는지 확인할 예정
- ⚠️ 유저가 커뮤니티에 가입할 때, `isFirstInCommunity` 칼럼에 `false` 가 들어가도록 수정하여야 함. @aaa22220304 
- `CommunityUser` Table의 `isFirstInCommunity`값을 변경할 수 있는 API, PUT '/user/first-visit'(가제) 구현 예정

[Feat] GET 'user/me' API 반환값 수정

---

rest/src/main/java/com/waglewagle/rest/thread/Thread.java
rest/src/main/java/com/waglewagle/rest/thread/ThreadController.java
rest/src/main/java/com/waglewagle/rest/thread/ThreadDTO.java
rest/src/main/java/com/waglewagle/rest/thread/ThreadRepository.java
rest/src/main/java/com/waglewagle/rest/thread/ThreadService.java
rest/src/main/java/com/waglewagle/rest/user/dto/AuthorDTO.java

```
POST
/api/v1/thread
Request: 
- 인증 쿠키(user-id), 
- {
keywordId: string
parentThreadId: string | null (*null은 “parentThreadId” = null 이 아닌, 키가 아예 없어야 됩니다.)
content: string
}
Response:
{
success: boolean
}
```
```
DELETE
/api/v1/thread
Request:
- 인증 쿠키(user-id)
- {
threadId: string
}
Response:
{
success: boolean
}
```
- Spring Data JPA로 Repository 변경
- 자식 스레드들 삭제 쿼리 재귀적 쿼리 호출에서 단일 쿼리로 변경
- thread 조회(GET method) API 구현
- 입력 Validation, 예외 처리, 그리고 테스트 코드 작성

[Feat] 스레드 생성/삭제 API POST '/api/v1/thread', DELETE '/api/v1/thread' 구현

---

rest/src/main/java/com/waglewagle/rest/communityUser/CommunityUser.java
rest/src/main/java/com/waglewagle/rest/communityUser/CommunityUserController.java
rest/src/main/java/com/waglewagle/rest/communityUser/CommunityUserDTO.java
rest/src/main/java/com/waglewagle/rest/communityUser/CommunityUserService.java

```
PUT
/api/v1/community-user/{community_id}/profile
Request: 
- 인증 쿠키(user-id), 
- {
profileImageUrl: string
username: string
}
Response:
- 성공: status code 200
- 실패: status code 400
```
```
PUT
/api/v1/community-user/123/first-visit
Request:
- 인증 쿠키(user-id)
Response:
- 성공: status code 200
- 실패: status code 400
```
- community_user 테이블 is_first_visit 컬럼 추가
- 최초 가입 시 true로 설정
- API 요청으로 false로 설정
- 커뮤니티 프로필 변경 API
- 각 필드에 null이 있다면, null로 변경됨.
- keyword 도메인
- `GET` /api/v1/keyword/user/{community_id}
- 커뮤니티 내 내가 가진 키워드

[feat] 커뮤니티 최초 가입 컬럼 및 변경 API, 커뮤니티 프로필 변경 API 추가

---

rest/src/main/java/com/waglewagle/rest/communityUser/CommunityUser.java
rest/src/main/java/com/waglewagle/rest/communityUser/CommunityUserController.java
rest/src/main/java/com/waglewagle/rest/communityUser/CommunityUserDTO.java
rest/src/main/java/com/waglewagle/rest/communityUser/CommunityUserService.java
rest/src/main/java/com/waglewagle/rest/keyword/KeywordController.java
rest/src/main/java/com/waglewagle/rest/keyword/KeywordDTO.java
rest/src/main/java/com/waglewagle/rest/keyword/KeywordRepository.java
rest/src/main/java/com/waglewagle/rest/keyword/KeywordService.java
rest/src/main/java/com/waglewagle/rest/keyword/association/DumbAssociateCalculator.java

```
GET
/api/v1/keyword/user/{community_id}
Request: 
- 인증 쿠키(user-id), 
- URL path parameter community_id
Response:
- 성공: status code 200
- Array<{
keywordId: string
keywordName: string
}>
- 실패: status code 400
```
- 커뮤니티 내 내가 참가한 키워드 API
- 키워드 추천 API 상위 10개 키워드만 반환하도록 변경
- 커뮤니티 내 키워드 API N+1 문제 해결

[feat] 커뮤니티 내 내가 선택한 키워드 API 및 키워드 추천 API 반환 개수 수정

---

rest/src/main/java/com/waglewagle/rest/keyword/KeywordService.java
rest/src/main/java/com/waglewagle/rest/thread/Thread.java
rest/src/main/java/com/waglewagle/rest/thread/ThreadController.java
rest/src/main/java/com/waglewagle/rest/thread/ThreadDTO.java
rest/src/main/java/com/waglewagle/rest/thread/ThreadRepository.java
rest/src/main/java/com/waglewagle/rest/thread/ThreadService.java

```
GET
api/v1/thread/keyword?keyword-id=???
Request: 
- query parameter keyword-id: number
Response:
- 성공: status code 200 || 204 (빈 Array)
- Array<{
threadId: string
content: string
createdAt: string (date format)
updatedAt: string (date format)
author: {
userId: string
username: string
profileImageUrl: string
}
childThreads: {
threadId: string
content: string
createdAt: string (date format)
updatedAt: string (date format)
author: {
userId: string
username: string
profileImageUrl: string
}
childThreads: null
childThreadCount: null
}
childThreadCount: number
}>
- 실패: status code 400
```
- 쓰레드 Entity가 children 멤버 변수에 자기 자신을 참조하던 버그 수정
- 키워드 내 쓰레드 API

[feat] 키워드 내 전체 스레드 조회 API

---

rest/src/main/java/com/waglewagle/rest/user/User.java
rest/src/main/java/com/waglewagle/rest/user/UserController.java
rest/src/main/java/com/waglewagle/rest/user/UserRepository.java
rest/src/main/java/com/waglewagle/rest/user/UserService.java
rest/src/main/java/com/waglewagle/rest/user/dto/UserConnectionStatusDTO.java

```
PUT
api/v1/user/last-activity
Response Body
null
```
```
GET
api/v1/user/keyword
Query params
keyword-id: number
Response Body
Array<{
userId: string
username: string
profileImageUrl: string
lastActivity: string (YYYY-MM-DD\T\HH:MM:SS) ( ex) "2022-12-04T14:20:48" )
}>
```
```
GET
api/v1/user/community
Query params
community-id: number
Response Body
Array<{
userId: string
username: string
profileImageUrl: string
lastActivity: string (YYYY-MM-DD\T\HH:MM:SS) ( ex) "2022-12-04T14:20:48" )
}>
```
- 같은 커뮤니티 혹은 키워드 그룹 내에서 다른 사용자의 접속 상태를 확인할 수 있는 방법이 없었음.
- User entity에 last-activity 컬럼 추가
- default는 CURRENT_TIMESTAMP
- 해당 컬럼을 변경할 수 있는 API 추가
- 해당 컬럼의 정보를 포함하여 특정 그룹 내의 유저들의 정보를 얻을 수 있는 API 추가

[feat] 유저 최근 활동 시간 컬럼 및 api 추가

---

oauth/package.json
oauth/src/domain/oauth/oauth.service.ts
oauth/src/domain/oauth/user.entity.ts
oauth/src/domain/oauth/user.repository.ts
oauth/src/enum/roll.enum.ts
oauth/src/util/utils.ts

- User entity의 일부 컬럼 추가
- oauth 서버에서 User 엔티티의 일부 column이 반영되어 있지 않던 문제가 있었음.
- Oauth server의 User entity에 다음 컬럼 추가
- last_activity
- default CURRENT_TIMESTAMP
- role
- default USER
- email

[feat] oauth user entity에 last_activity 필드 추가

---

rest/src/main/java/com/waglewagle/rest/keyword/KeywordRepository.java

JPA N+1 문제 해결 과정에서, 카테시안 곱 현상이 발생함
쿼리문에 distinct 키워드를 추가하여 해결

[fix] 커뮤니티내 전체 키워드 리스트 조회 API (GET /keyword/community-id) 객체 중복 조회 해결

---

rest/src/main/java/com/waglewagle/rest/common/error/GlobalExceptionHandler.java
rest/src/main/java/com/waglewagle/rest/keyword/exception/ExceptionMessage.java
rest/src/main/java/com/waglewagle/rest/keyword/exception/NoSuchKeywordException.java

- 컨트롤러의 에러를 전역적으로 처리해주는 `GlobalExceptionHandler`를 구현.
- 도메인 아래의 에러들을 어떻게 처리할지에 대해 룰을 정함.
1. 서비스 레이어의 메서드 들에 대한 단위 테스트를 짜려고 하는데, 컨트롤러에 관심사가 너무 몰려있어(서비스 레이어 메서드 여럿을 컨트롤러에서 호출 중), 단위 테스트로 구성하기에 부적합하였음.
2. 컨트롤러 메서드의 관심사를 서비스 레이어로 내려, 서비스 레이어 메소드들 각각에 대해 단위 테스트를 구성하고자 함.
3. 서비스 메서드가 가지고 있는 분기가, 값을 반환하는 성공 분기, 예외를 throw하는 실패 분기로 나뉘고, 실패 분기는 다시 여러 유형의 예외로 나뉜다.
\>>  **난립하는 커스텀 에러와 에러 메세지, try-catch로 뚱뚱해지는 컨트롤러 메서드
- Spring의 전역 예외 관리 방법인, `@RestControlllerAdvice`와 `@ExceptionHandler` 사용하였음.
- 바뀐 구조를 기반으로 API 코드 리팩토링, 이후 단위 테스트 작성

[Feat] 전역 ExceptionHandler 구현(+예시 하나)

---

rest/src/main/java/com/waglewagle/rest/community/repository/custom/CommunityUserCustomRepository.java
rest/src/main/java/com/waglewagle/rest/community/repository/custom/CommunityUserCustomRepositoryImpl.java
rest/src/main/java/com/waglewagle/rest/community/service/CommunityUserService.java
rest/src/main/java/com/waglewagle/rest/keyword/controller/KeywordController.java
rest/src/main/java/com/waglewagle/rest/keyword/repository/KeywordRepository.java
rest/src/main/java/com/waglewagle/rest/keyword/service/KeywordService.java
rest/src/main/java/com/waglewagle/rest/keyword/service/KeywordUserService.java
rest/src/main/java/com/waglewagle/rest/thread/controller/ThreadController.java
rest/src/main/java/com/waglewagle/rest/thread/data_object/dto/request/ThreadRequest.java
rest/src/main/java/com/waglewagle/rest/thread/repository/custom/ThreadCustomRepositoryImpl.java
rest/src/main/java/com/waglewagle/rest/thread/service/ThreadService.java
rest/src/main/java/com/waglewagle/rest/user/controller/UserController.java
rest/src/main/java/com/waglewagle/rest/user/entity/User.java
rest/src/main/java/com/waglewagle/rest/user/repository/custom/UserCustomRepositoryImpl.java
rest/src/main/java/com/waglewagle/rest/user/service/UserService.java
rest/src/test/java/com/waglewagle/rest/thread/ThreadServiceTest.java

1. Validation 로직이 controller에서 service로 이동함.
2. Optional 객체를 사용하여 validation 진행
3. 추후 custom exception을 활용하여 throw되는 exception을 대체할 예정
1. validation 로직이 controller에서 진행되면, 같은 transaction 내에서 validation이 진행되지 않는다.
2. 또한, test code를 작성하기에 controller의 관심사가 너무 크다.
3. service layer에서 throw한 exception은 exception handler로 이동하게 될 것이므로, 관심사를 분리할 수 있다.
4. Optional 객체를 활용한 함수형 프로그래밍으로 효과적으로 validation을 진행할 수 있다.

[refactor] validation 로직을 controller에서 service로 이동, Optional 사용 증가

---

rest/src/main/java/com/waglewagle/rest/common/exception/ExceptionMessage.java
rest/src/main/java/com/waglewagle/rest/common/exception/InvalidInputException.java
rest/src/main/java/com/waglewagle/rest/community/controller/CommunityUserController.java
rest/src/main/java/com/waglewagle/rest/community/exception/AlreadyJoinedCommunityException.java
rest/src/main/java/com/waglewagle/rest/community/exception/ExceptionMessage.java
rest/src/main/java/com/waglewagle/rest/community/exception/NoSuchCommunityException.java
rest/src/main/java/com/waglewagle/rest/community/exception/UnSubscribedCommunityException.java
rest/src/main/java/com/waglewagle/rest/community/service/CommunityService.java
rest/src/main/java/com/waglewagle/rest/community/service/CommunityUserService.java
rest/src/main/java/com/waglewagle/rest/keyword/exception/AlreadyJoinedKeywordException.java
rest/src/main/java/com/waglewagle/rest/keyword/exception/ExceptionMessage.java
rest/src/main/java/com/waglewagle/rest/thread/controller/ThreadController.java
rest/src/main/java/com/waglewagle/rest/thread/exception/ExceptionMessage.java
rest/src/main/java/com/waglewagle/rest/thread/exception/InvalidThreadException.java
rest/src/main/java/com/waglewagle/rest/thread/exception/NoSuchThreadException.java
rest/src/main/java/com/waglewagle/rest/thread/service/ThreadService.java
rest/src/main/java/com/waglewagle/rest/user/controller/UserController.java
rest/src/main/java/com/waglewagle/rest/user/exception/DuplicatedUsernameException.java
rest/src/main/java/com/waglewagle/rest/user/exception/ExceptionMessage.java
rest/src/main/java/com/waglewagle/rest/user/exception/NoSuchUserException.java
rest/src/main/java/com/waglewagle/rest/user/exception/UnauthorizedException.java
rest/src/main/java/com/waglewagle/rest/user/repository/custom/UserCustomRepositoryImpl.java
rest/src/main/java/com/waglewagle/rest/user/service/UserService.java
rest/src/main/resources/logback-spring.xml

1. 각 도메인에 대하여 Exception 추가
2. 각 도메인에 대하여 enum ExceptionMessage 추가
3. validation 로직 controller에서 service layer로 이동
1. transaction을 고려하여 validation 로직 이동.
2. 예외 처리에 대한 관심사가 service layer에 있는 것은, 너무 많은 관심사로 판단.
3. exception을 일괄적으로 관리하기 위해서는 enum으로 message를 관리하고, custom exception을 만드는 것이 좋다고 판단.
- custom exception이 아니라면, 정말 internal server error라고 판단.
1. 생성된 Exception
- common
- InvalidInputException
- Keyword
- AlreadyJoinedKeywordException
- NoSuchKeywordException
- User
- DuplicatedUsernameException
- NoSuchUserException
- UnauthorizedException
- Thread
- InvalidThreadException
- NoSuchThreadException
- Community
- AlreadyJoinedCommunityException
- NoSuchCommunityException
- UnSubscribedCommunityException
1. 테스트 코드 작성 및 keyword 도메인 비즈니스 로직 점검

[refactor] validation 로직 이동 및 exception을 throw하는 방식으로 변경

---

rest/src/main/java/com/waglewagle/rest/keyword/service/KeywordService.java

내가 참여한 커뮤니티를 조회하던 과정에서 있던 validation 로직 오류 수정
내가 참여한 커뮤니티를 검증하는 과정에서 논리적 오류가 있어서 정상적인 상황에서 exception이 발생하는 버그가 있었음
내가 참여한 커뮤니티를 조회하던 과정에서 있던 validation 로직 오류 수정

[hotfix] validation 로직이 거꾸로 되어 에러가 발생하던 문제 해결

---

frontend/hooks/keyword/useRelatedKeywordList.tsx

- prevKeywordData가 optional로 오기 때문에 발생하던 에러
- useQuery 내부에서 enabled를 설정하여 해결함.

[fix] useRelatedKeywordList 버그 해결

---

rest/src/main/java/com/waglewagle/rest/keyword/service/KeywordService.java

키워드가 존재하지 않아도 생성할 수 없던 버그 수정
커뮤니티에 키워드가 존재하지 않아도 생성할 수 없었음
Optional 객체에 대한 Optional 객체를 만들어 validation을 진행하던 버그 수정

[fix] 키워드가 존재하지 않아도 생성할 수 없던 버그 수정

---

rest/src/main/java/com/waglewagle/rest/common/error/GlobalExceptionHandler.java
rest/src/main/java/com/waglewagle/rest/keyword/service/KeywordService.java
rest/src/test/java/com/waglewagle/rest/keyword/service/KeywordServiceTest.java

- 각 도메인 별 exception 대응 메서드 추가
- 기존 exception 대응 메서드가 없어서 Internal Server Error가 발생했었음
- 총 11가지 custom Exception 대응 메서드 추가

[feat] exception handler 대응 exception 추가

---

frontend/apis/user.ts
frontend/components/admin/AdminMain.tsx
frontend/components/admin/UserControl.tsx
frontend/components/community/CommunityHeader.tsx
frontend/components/main/CommunityItem.tsx
frontend/components/main/MainTitle.tsx
frontend/pages/admin/[id].tsx
frontend/sass/components/admin/AdminMain.module.scss
frontend/sass/components/admin/AdminSidebar.module.scss
frontend/sass/components/admin/KeywordControl.module.scss
frontend/sass/components/common/DefaultButton.module.scss
frontend/sass/components/common/LoginModalContent.module.scss
frontend/sass/components/community/keyword-bubble-chart/KeywordBubble.module.scss
frontend/sass/components/main/CommunityItem.module.scss
frontend/sass/components/main/MainLayout.module.scss

- 커뮤니티 아이템 UI 수정
- 메인 페이지 사용자 이름 UI 수정 
- 랜딩 페이지 시작하기 UI 수정
- 메인페이지 a태그 Link로 변경
- 커뮤니티 로고 클릭시 메인 페이지 이동
- Bubble Hover 시 다른 원 위로 표시되지 않는 현상 해결
- 관리자 페이지 스타일 수정
- 관리자 페이지 커뮤니티 유저 목록 표시

[Chore] 스타일 수정

---

rest/src/main/java/com/waglewagle/rest/community/data_object/dto/response/CommunityResponse.java
rest/src/main/java/com/waglewagle/rest/community/repository/custom/CommunityUserCustomRepository.java
rest/src/main/java/com/waglewagle/rest/community/repository/custom/CommunityUserCustomRepositoryImpl.java
rest/src/main/java/com/waglewagle/rest/community/service/CommunityService.java

- 내가 참여한 커뮤니티 API 멤버 수 필드 추가
- 내가 참여한 커뮤니티의 멤버 수를 알 수 없었음
- 내가 참여한 커뮤니티의 id들을 기준으로 하여 communityUser entitiy를 가져오는 메서드 생성
- 해당 메서드를 모두 communityDTO와 mapping하여 반환

[feat] 내가 참여한 커뮤니티 멤버 수 API
